#import "Basic";
#import "Basic";
// #import "Compiler";
// #import "String";
// #import "stb_image";

main :: () {
	// x, y, comp : s32;
	// cstr_path := to_c_string("test.png");
	// data := stbi_load(cstr_path, *x, *y, *comp, 3);

	// print("x = %, y = %\n", x, y);

	// data :[]u8= .[xx #char "a", xx #char "b", xx #char "c", xx 0, xx #char "d"];
	// str := to_string(data.data);
	// print("%\n", str);
}
